# Generated by Django 4.2 on 2023-05-10 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webGrupoCero', '0002_obra_foto'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='foto',
            field=models.ImageField(null=True, upload_to='foto'),
        ),
    ]
