# Generated by Django 4.2 on 2023-05-23 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webGrupoCero', '0005_contacto'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
