# Generated by Django 4.2 on 2023-06-28 01:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('webGrupoCero', '0006_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Galeria',
            fields=[
                ('idFoto', models.AutoField(primary_key=True, serialize=False)),
                ('foto', models.ImageField(null=True, upload_to='foto')),
                ('obra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webGrupoCero.obra')),
            ],
        ),
    ]
