# Generated by Django 4.2 on 2023-06-28 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webGrupoCero', '0007_galeria'),
    ]

    operations = [
        migrations.AddField(
            model_name='obra',
            name='precio',
            field=models.IntegerField(default=100),
        ),
    ]
